### ISSUE TITLE
Uncaught exception when the app is launched and the PC is offline

### ISSUE THREAD

**Issue by Enrico204** [Enrico204/Whatsapp-Desktop#48]
If there is no network connection, and Whatsapp-Desktop is launched, then an error message pops-up:

    Uncaught Exception:
    TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/home/enrico/git/Whatsapp-Desktop/app/main.js:434:78)
    at self.callback (/home/enrico/git/Whatsapp-Desktop/app/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.onRequestError (/home/enrico/git/Whatsapp-Desktop/app/node_modules/request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)

**Comment by Defrilitus** [comment]
Error message still displays on macOS 10.13.2 when starting Whatsapp-Desktop without a working network connection (see #72).
