### ISSUE TITLE
Starting without internet causes Javascript error

### ISSUE THREAD

**Issue by Fincer** [Enrico204/Whatsapp-Desktop#67]
I have Whatsapp-desktop on my Arch Linux (x86_64). I runs fine unless I try to start the program without internet connection available. This leads to the following error:

```
Uncaught Exception:
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/opt/Whatsapp/resources/app/main.js:434:78)
    at self.callback (/opt/Whatsapp/resources/app/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.onRequestError (/opt/Whatsapp/resources/app/node_modules/request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
```

Re-enabling internet connection -> no issues

This is annoying because I have set the program auto-start during OS bootup. Practically, I don't never immediately have internet connection, so I encounter this issue every time I boot my computer. Currently, I have to either disable autostart or forcefully kill the program because of the error. I could write a short bash script which would check internet connection availability but I thought I'd be much better if the program itself could handle such situations.

Instead of Javascript error, I''d prefer some kind of "Error. No internet connection" or similar message appearing to the program main window with a "Retry" button, for example.

**Comment by Fincer** [comment]
Edit: Gash, there is already a closed issue for this. Checking newest program version and closing the issue. Sorry for troubling.

**Comment by Enrico204** [comment]
No problem, I'll deploy a new version asap :-)
