### ISSUE TITLE
Error at startup when network connection is not active.

### ISSUE THREAD

**Issue by Martin0707** [Enrico204/Whatsapp-Desktop#72]
### System details

* OS: Linux Mint 18.3 Sylvia
* App Version: github
* If Linux, Desktop Environment: cinnamon

### Expected behavior

No error

### Actual behavior

During startup, when network is not up, error message as follows:
```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/opt/whatsapp-desktop/resources/app/main.js:434:78)
    at self.callback (/opt/whatsapp-desktop/resources/app/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.onRequestError (/opt/whatsapp-desktop/resources/app/node_modules/request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
```

It is enough to close error window to continue normally.

### Step to reproduce the behavior

Enable autostart of WA Desktop and make sure you do not have network connection active at startup.

**Comment by Martin0707** [comment]
Enrico, you are right, using whatsapp-desktop_0.3.14-1_amd64.deb which is not built from latest and there are 14 commits to master since this release including fix requested. Please close this issue as it will be fixed with new package build. Thank you.

**Comment by Defrilitus** [comment]
Same here. Apologies.

**Comment by Enrico204** [comment]
No problem :-)
Stay tuned, I'll release a new version soon :-) :-)
