### ISSUE TITLE
App doesn't start

### ISSUE THREAD

**Issue by lucaoflaif** [Enrico204/Whatsapp-Desktop#85]
### System details

* OS: [Arch 4.14.8-1, English]
* App Version: [0.4.1, from AUR]
* If Linux, Desktop Environment: [KDE]

### Expected behavior

AUR package works correctly.

### Actual behavior

When I launch it from the .desktop file no window is showed.
I tried from the terminal and the output is

```bash
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'node-gettext'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/opt/Whatsapp/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /opt/Whatsapp/resources/app/main.js:11:23
    at Object.<anonymous> (/opt/Whatsapp/resources/app/main.js:810:3)
    at Object.<anonymous> (/opt/Whatsapp/resources/app/main.js:812:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```
### How I fix it

I launched ```npm install``` into the ```{pkgdir}/opt/Whatsapp/resources/app``` folder.
Now the app starts correctly.

**Comment by usernatilds** [comment]
Update to new version 0.4.2, this version fixed this.

**Comment by lucaoflaif** [comment]
Great! When the AUR package will be updated?

**Comment by bil-elmoussaoui** [comment]
@lucaoflaif I'm the maintainer of the AUR package. And it's already updated :) I try to keep update all the packages I maintain within 1/2 days at max.

**Comment by Enrico204** [comment]
Thanks @bil-elmoussaoui for keeping AUR updated :-)
